name: ex-api-dev
port: 8000

environment:
  ENV_NAME: "development"
  LOG_LEVEL: "debug"

commands:
  - "gunicorn --workers 1 --worker-class uvicorn.workers.UvicornWorker --timeout 0 --bind 0.0.0.0:8000 app:app"

dependencies:
  pypi:
    fastapi: ""
    gunicorn: ""
    uvicorn: ""

compute_pools:
  - c5-2x-deployment

auth:
  type: API

resources:
  cpu: "0.5"
  memory: "512Mi"
  ephemeralStorage: "1Gi"