name: ex-api-prod
port: 8000

environment:
  ENV_NAME: "production"
  LOG_LEVEL: "warning"

commands:
  - "gunicorn --workers 4 --worker-class uvicorn.workers.UvicornWorker --timeout 0 --bind 0.0.0.0:8000 app:app"

dependencies:
  pypi:
    fastapi: ""
    gunicorn: ""
    uvicorn: ""

compute_pools:
  - c5-2x-deployment

auth:
  type: API

resources:
  cpu: "2"
  memory: "2Gi"
  ephemeralStorage: "2Gi"