name: ex-api-staging
port: 8000

environment:
  ENV_NAME: "staging"
  LOG_LEVEL: "info"

commands:
  - "uvicorn app:app --host 0.0.0.0 --port 8000 --workers 2"

auth:
  type: API

compute_pools:
  - c5-2x-deployment

dependencies:
  pypi:
    fastapi: ""
    uvicorn: ""

resources:
  cpu: "1"
  memory: "1Gi"